// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.light.messenger.server;

public final class MessengerServer_Stub
    extends java.rmi.server.RemoteStub
    implements com.light.messenger.MessengerServerInf, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_chatExit_0;
    private static java.lang.reflect.Method $method_chatIdx_1;
    private static java.lang.reflect.Method $method_clientList_2;
    private static java.lang.reflect.Method $method_connectionUser_3;
    private static java.lang.reflect.Method $method_contactList_4;
    private static java.lang.reflect.Method $method_deleteDia_5;
    private static java.lang.reflect.Method $method_deleteFd_6;
    private static java.lang.reflect.Method $method_deleteMsg_7;
    private static java.lang.reflect.Method $method_deletegbk_8;
    private static java.lang.reflect.Method $method_deleteimg_9;
    private static java.lang.reflect.Method $method_fileUpdate_10;
    private static java.lang.reflect.Method $method_fileboo_11;
    private static java.lang.reflect.Method $method_fileboo2_12;
    private static java.lang.reflect.Method $method_fileinsert_13;
    private static java.lang.reflect.Method $method_filenamert_14;
    private static java.lang.reflect.Method $method_fileset_15;
    private static java.lang.reflect.Method $method_getUserList_16;
    private static java.lang.reflect.Method $method_idCheak_17;
    private static java.lang.reflect.Method $method_idReturn_18;
    private static java.lang.reflect.Method $method_insert_19;
    private static java.lang.reflect.Method $method_insert_20;
    private static java.lang.reflect.Method $method_insert_21;
    private static java.lang.reflect.Method $method_insertData_22;
    private static java.lang.reflect.Method $method_inviate_23;
    private static java.lang.reflect.Method $method_joinChat_24;
    private static java.lang.reflect.Method $method_loginCheck_25;
    private static java.lang.reflect.Method $method_makeNewChat_26;
    private static java.lang.reflect.Method $method_nicCheak_27;
    private static java.lang.reflect.Method $method_pwReturn_28;
    private static java.lang.reflect.Method $method_search_29;
    private static java.lang.reflect.Method $method_selectHp_30;
    private static java.lang.reflect.Method $method_selectMem_31;
    private static java.lang.reflect.Method $method_selectMem_32;
    private static java.lang.reflect.Method $method_selectMsgList_33;
    private static java.lang.reflect.Method $method_selectmemList_34;
    private static java.lang.reflect.Method $method_sendImg_35;
    private static java.lang.reflect.Method $method_setChatMsg_36;
    private static java.lang.reflect.Method $method_setMsg_37;
    private static java.lang.reflect.Method $method_setTabledata_38;
    private static java.lang.reflect.Method $method_setTabledata_39;
    private static java.lang.reflect.Method $method_setTabledata_40;
    private static java.lang.reflect.Method $method_setTabledataDia_41;
    private static java.lang.reflect.Method $method_setTabledataGbk_42;
    private static java.lang.reflect.Method $method_setTabledataimg_43;
    private static java.lang.reflect.Method $method_update_44;
    private static java.lang.reflect.Method $method_update_45;
    private static java.lang.reflect.Method $method_update_46;
    private static java.lang.reflect.Method $method_update_47;
    private static java.lang.reflect.Method $method_update_48;
    private static java.lang.reflect.Method $method_updateMsg_49;
    private static java.lang.reflect.Method $method_userOnOff_50;
    private static java.lang.reflect.Method $method_userSave_51;
    private static java.lang.reflect.Method $method_userlogOut_52;
    
    static {
	try {
	    $method_chatExit_0 = com.light.messenger.MessengerServerInf.class.getMethod("chatExit", new java.lang.Class[] {java.lang.String.class, int.class});
	    $method_chatIdx_1 = com.light.messenger.MessengerServerInf.class.getMethod("chatIdx", new java.lang.Class[] {java.lang.String.class});
	    $method_clientList_2 = com.light.messenger.MessengerServerInf.class.getMethod("clientList", new java.lang.Class[] {java.lang.String.class});
	    $method_connectionUser_3 = com.light.messenger.MessengerServerInf.class.getMethod("connectionUser", new java.lang.Class[] {java.lang.String.class});
	    $method_contactList_4 = com.light.messenger.MessengerServerInf.class.getMethod("contactList", new java.lang.Class[] {java.lang.String.class, com.light.messenger.MessengerClientInf.class});
	    $method_deleteDia_5 = com.light.messenger.MessengerServerInf.class.getMethod("deleteDia", new java.lang.Class[] {java.lang.String.class});
	    $method_deleteFd_6 = com.light.messenger.MessengerServerInf.class.getMethod("deleteFd", new java.lang.Class[] {java.lang.String.class});
	    $method_deleteMsg_7 = com.light.messenger.MessengerServerInf.class.getMethod("deleteMsg", new java.lang.Class[] {java.lang.String.class});
	    $method_deletegbk_8 = com.light.messenger.MessengerServerInf.class.getMethod("deletegbk", new java.lang.Class[] {java.lang.String.class});
	    $method_deleteimg_9 = com.light.messenger.MessengerServerInf.class.getMethod("deleteimg", new java.lang.Class[] {java.lang.String.class});
	    $method_fileUpdate_10 = com.light.messenger.MessengerServerInf.class.getMethod("fileUpdate", new java.lang.Class[] {java.lang.String.class});
	    $method_fileboo_11 = com.light.messenger.MessengerServerInf.class.getMethod("fileboo", new java.lang.Class[] {java.lang.String.class});
	    $method_fileboo2_12 = com.light.messenger.MessengerServerInf.class.getMethod("fileboo2", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	    $method_fileinsert_13 = com.light.messenger.MessengerServerInf.class.getMethod("fileinsert", new java.lang.Class[] {});
	    $method_filenamert_14 = com.light.messenger.MessengerServerInf.class.getMethod("filenamert", new java.lang.Class[] {});
	    $method_fileset_15 = com.light.messenger.MessengerServerInf.class.getMethod("fileset", new java.lang.Class[] {java.lang.String.class});
	    $method_getUserList_16 = com.light.messenger.MessengerServerInf.class.getMethod("getUserList", new java.lang.Class[] {java.lang.String.class});
	    $method_idCheak_17 = com.light.messenger.MessengerServerInf.class.getMethod("idCheak", new java.lang.Class[] {java.lang.String.class});
	    $method_idReturn_18 = com.light.messenger.MessengerServerInf.class.getMethod("idReturn", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	    $method_insert_19 = com.light.messenger.MessengerServerInf.class.getMethod("insert", new java.lang.Class[] {com.light.vo.DiaVO.class});
	    $method_insert_20 = com.light.messenger.MessengerServerInf.class.getMethod("insert", new java.lang.Class[] {com.light.vo.GbkVO.class});
	    $method_insert_21 = com.light.messenger.MessengerServerInf.class.getMethod("insert", new java.lang.Class[] {com.light.vo.ImgVO.class});
	    $method_insertData_22 = com.light.messenger.MessengerServerInf.class.getMethod("insertData", new java.lang.Class[] {java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class});
	    $method_inviate_23 = com.light.messenger.MessengerServerInf.class.getMethod("inviate", new java.lang.Class[] {java.lang.String.class, java.lang.String.class, int.class});
	    $method_joinChat_24 = com.light.messenger.MessengerServerInf.class.getMethod("joinChat", new java.lang.Class[] {int.class, int.class, java.lang.String.class, java.util.ArrayList.class, java.util.ArrayList.class});
	    $method_loginCheck_25 = com.light.messenger.MessengerServerInf.class.getMethod("loginCheck", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	    $method_makeNewChat_26 = com.light.messenger.MessengerServerInf.class.getMethod("makeNewChat", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	    $method_nicCheak_27 = com.light.messenger.MessengerServerInf.class.getMethod("nicCheak", new java.lang.Class[] {java.lang.String.class});
	    $method_pwReturn_28 = com.light.messenger.MessengerServerInf.class.getMethod("pwReturn", new java.lang.Class[] {java.lang.String.class, java.lang.String.class, java.lang.String.class});
	    $method_search_29 = com.light.messenger.MessengerServerInf.class.getMethod("search", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	    $method_selectHp_30 = com.light.messenger.MessengerServerInf.class.getMethod("selectHp", new java.lang.Class[] {com.light.vo.HpVO.class});
	    $method_selectMem_31 = com.light.messenger.MessengerServerInf.class.getMethod("selectMem", new java.lang.Class[] {});
	    $method_selectMem_32 = com.light.messenger.MessengerServerInf.class.getMethod("selectMem", new java.lang.Class[] {java.lang.String.class});
	    $method_selectMsgList_33 = com.light.messenger.MessengerServerInf.class.getMethod("selectMsgList", new java.lang.Class[] {com.light.vo.MsgVO.class});
	    $method_selectmemList_34 = com.light.messenger.MessengerServerInf.class.getMethod("selectmemList", new java.lang.Class[] {com.light.vo.MemVO.class});
	    $method_sendImg_35 = com.light.messenger.MessengerServerInf.class.getMethod("sendImg", new java.lang.Class[] {java.lang.String.class, int.class});
	    $method_setChatMsg_36 = com.light.messenger.MessengerServerInf.class.getMethod("setChatMsg", new java.lang.Class[] {int.class, java.lang.String.class});
	    $method_setMsg_37 = com.light.messenger.MessengerServerInf.class.getMethod("setMsg", new java.lang.Class[] {java.lang.String.class, java.lang.String.class, java.lang.String.class});
	    $method_setTabledata_38 = com.light.messenger.MessengerServerInf.class.getMethod("setTabledata", new java.lang.Class[] {com.light.vo.DiaVO.class});
	    $method_setTabledata_39 = com.light.messenger.MessengerServerInf.class.getMethod("setTabledata", new java.lang.Class[] {com.light.vo.GbkVO.class});
	    $method_setTabledata_40 = com.light.messenger.MessengerServerInf.class.getMethod("setTabledata", new java.lang.Class[] {com.light.vo.ImgVO.class});
	    $method_setTabledataDia_41 = com.light.messenger.MessengerServerInf.class.getMethod("setTabledataDia", new java.lang.Class[] {});
	    $method_setTabledataGbk_42 = com.light.messenger.MessengerServerInf.class.getMethod("setTabledataGbk", new java.lang.Class[] {});
	    $method_setTabledataimg_43 = com.light.messenger.MessengerServerInf.class.getMethod("setTabledataimg", new java.lang.Class[] {});
	    $method_update_44 = com.light.messenger.MessengerServerInf.class.getMethod("update", new java.lang.Class[] {com.light.vo.DiaVO.class});
	    $method_update_45 = com.light.messenger.MessengerServerInf.class.getMethod("update", new java.lang.Class[] {com.light.vo.GbkVO.class});
	    $method_update_46 = com.light.messenger.MessengerServerInf.class.getMethod("update", new java.lang.Class[] {com.light.vo.HpVO.class});
	    $method_update_47 = com.light.messenger.MessengerServerInf.class.getMethod("update", new java.lang.Class[] {com.light.vo.ImgVO.class});
	    $method_update_48 = com.light.messenger.MessengerServerInf.class.getMethod("update", new java.lang.Class[] {com.light.vo.MemVO.class});
	    $method_updateMsg_49 = com.light.messenger.MessengerServerInf.class.getMethod("updateMsg", new java.lang.Class[] {com.light.vo.MsgVO.class});
	    $method_userOnOff_50 = com.light.messenger.MessengerServerInf.class.getMethod("userOnOff", new java.lang.Class[] {java.lang.String.class});
	    $method_userSave_51 = com.light.messenger.MessengerServerInf.class.getMethod("userSave", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	    $method_userlogOut_52 = com.light.messenger.MessengerServerInf.class.getMethod("userlogOut", new java.lang.Class[] {java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public MessengerServer_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of chatExit(String, int)
    public void chatExit(java.lang.String $param_String_1, int $param_int_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_chatExit_0, new java.lang.Object[] {$param_String_1, new java.lang.Integer($param_int_2)}, 3729804328272879088L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of chatIdx(String)
    public int chatIdx(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_chatIdx_1, new java.lang.Object[] {$param_String_1}, 2225439543556199557L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of clientList(String)
    public java.util.ArrayList clientList(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_clientList_2, new java.lang.Object[] {$param_String_1}, 2109258033716030523L);
	    return ((java.util.ArrayList) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of connectionUser(String)
    public java.util.List connectionUser(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_connectionUser_3, new java.lang.Object[] {$param_String_1}, 535344897787884050L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of contactList(String, MessengerClientInf)
    public void contactList(java.lang.String $param_String_1, com.light.messenger.MessengerClientInf $param_MessengerClientInf_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_contactList_4, new java.lang.Object[] {$param_String_1, $param_MessengerClientInf_2}, 7548252418318951405L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of deleteDia(String)
    public void deleteDia(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_deleteDia_5, new java.lang.Object[] {$param_String_1}, 4932059844723357390L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of deleteFd(String)
    public void deleteFd(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_deleteFd_6, new java.lang.Object[] {$param_String_1}, 7521792405866879014L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of deleteMsg(String)
    public void deleteMsg(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_deleteMsg_7, new java.lang.Object[] {$param_String_1}, 2984396338402548381L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of deletegbk(String)
    public void deletegbk(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_deletegbk_8, new java.lang.Object[] {$param_String_1}, -7270077389372823369L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of deleteimg(String)
    public void deleteimg(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_deleteimg_9, new java.lang.Object[] {$param_String_1}, -2606163509633122066L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of fileUpdate(String)
    public void fileUpdate(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_fileUpdate_10, new java.lang.Object[] {$param_String_1}, -2545503913733808825L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of fileboo(String)
    public void fileboo(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_fileboo_11, new java.lang.Object[] {$param_String_1}, -4503851361651807681L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of fileboo2(String, String)
    public void fileboo2(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_fileboo2_12, new java.lang.Object[] {$param_String_1, $param_String_2}, 6635847923017840749L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of fileinsert()
    public java.lang.String fileinsert()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_fileinsert_13, null, 6583079613461078120L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of filenamert()
    public java.lang.String filenamert()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_filenamert_14, null, 106832092577062465L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of fileset(String)
    public void fileset(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_fileset_15, new java.lang.Object[] {$param_String_1}, -3013368996442480285L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getUserList(String)
    public java.util.List getUserList(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getUserList_16, new java.lang.Object[] {$param_String_1}, -1675830052044000462L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of idCheak(String)
    public boolean idCheak(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_idCheak_17, new java.lang.Object[] {$param_String_1}, -7816963633554143941L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of idReturn(String, String)
    public java.lang.String idReturn(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_idReturn_18, new java.lang.Object[] {$param_String_1, $param_String_2}, -4204540800709576812L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of insert(DiaVO)
    public void insert(com.light.vo.DiaVO $param_DiaVO_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_insert_19, new java.lang.Object[] {$param_DiaVO_1}, -6939967547780116214L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of insert(GbkVO)
    public void insert(com.light.vo.GbkVO $param_GbkVO_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_insert_20, new java.lang.Object[] {$param_GbkVO_1}, -3522456419048523658L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of insert(ImgVO)
    public void insert(com.light.vo.ImgVO $param_ImgVO_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_insert_21, new java.lang.Object[] {$param_ImgVO_1}, 484560473850781534L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of insertData(String, String, String, String, String, String, String, String, String)
    public void insertData(java.lang.String $param_String_1, java.lang.String $param_String_2, java.lang.String $param_String_3, java.lang.String $param_String_4, java.lang.String $param_String_5, java.lang.String $param_String_6, java.lang.String $param_String_7, java.lang.String $param_String_8, java.lang.String $param_String_9)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_insertData_22, new java.lang.Object[] {$param_String_1, $param_String_2, $param_String_3, $param_String_4, $param_String_5, $param_String_6, $param_String_7, $param_String_8, $param_String_9}, -8861320107141634887L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of inviate(String, String, int)
    public void inviate(java.lang.String $param_String_1, java.lang.String $param_String_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_inviate_23, new java.lang.Object[] {$param_String_1, $param_String_2, new java.lang.Integer($param_int_3)}, -7477908170391432099L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of joinChat(int, int, String, ArrayList, ArrayList)
    public void joinChat(int $param_int_1, int $param_int_2, java.lang.String $param_String_3, java.util.ArrayList $param_ArrayList_4, java.util.ArrayList $param_ArrayList_5)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_joinChat_24, new java.lang.Object[] {new java.lang.Integer($param_int_1), new java.lang.Integer($param_int_2), $param_String_3, $param_ArrayList_4, $param_ArrayList_5}, -7726682445936915019L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of loginCheck(String, String)
    public boolean loginCheck(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_loginCheck_25, new java.lang.Object[] {$param_String_1, $param_String_2}, -2365406233765538466L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of makeNewChat(String, String)
    public int makeNewChat(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_makeNewChat_26, new java.lang.Object[] {$param_String_1, $param_String_2}, -6428228693393141589L);
	    return ((java.lang.Integer) $result).intValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of nicCheak(String)
    public boolean nicCheak(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_nicCheak_27, new java.lang.Object[] {$param_String_1}, 7122720818479023153L);
	    return ((java.lang.Boolean) $result).booleanValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of pwReturn(String, String, String)
    public java.lang.String pwReturn(java.lang.String $param_String_1, java.lang.String $param_String_2, java.lang.String $param_String_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_pwReturn_28, new java.lang.Object[] {$param_String_1, $param_String_2, $param_String_3}, -8542300979026461224L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of search(String, String)
    public java.util.List search(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_search_29, new java.lang.Object[] {$param_String_1, $param_String_2}, 7641652855372758988L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of selectHp(HpVO)
    public java.util.List selectHp(com.light.vo.HpVO $param_HpVO_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_selectHp_30, new java.lang.Object[] {$param_HpVO_1}, 2253253286697979977L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of selectMem()
    public java.util.List selectMem()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_selectMem_31, null, -1435737507054679894L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of selectMem(String)
    public java.util.List selectMem(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_selectMem_32, new java.lang.Object[] {$param_String_1}, -3955431271301498788L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of selectMsgList(MsgVO)
    public java.util.List selectMsgList(com.light.vo.MsgVO $param_MsgVO_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_selectMsgList_33, new java.lang.Object[] {$param_MsgVO_1}, -8593630319936373510L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of selectmemList(MemVO)
    public java.util.List selectmemList(com.light.vo.MemVO $param_MemVO_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_selectmemList_34, new java.lang.Object[] {$param_MemVO_1}, 3411293562202157468L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of sendImg(String, int)
    public void sendImg(java.lang.String $param_String_1, int $param_int_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_sendImg_35, new java.lang.Object[] {$param_String_1, new java.lang.Integer($param_int_2)}, 8897026541112585142L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setChatMsg(int, String)
    public void setChatMsg(int $param_int_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setChatMsg_36, new java.lang.Object[] {new java.lang.Integer($param_int_1), $param_String_2}, -5317451018867107027L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setMsg(String, String, String)
    public void setMsg(java.lang.String $param_String_1, java.lang.String $param_String_2, java.lang.String $param_String_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_setMsg_37, new java.lang.Object[] {$param_String_1, $param_String_2, $param_String_3}, -8714908731401204375L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setTabledata(DiaVO)
    public java.util.List setTabledata(com.light.vo.DiaVO $param_DiaVO_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_setTabledata_38, new java.lang.Object[] {$param_DiaVO_1}, 1617011781201282238L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setTabledata(GbkVO)
    public java.util.List setTabledata(com.light.vo.GbkVO $param_GbkVO_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_setTabledata_39, new java.lang.Object[] {$param_GbkVO_1}, 3726783637423539792L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setTabledata(ImgVO)
    public java.util.List setTabledata(com.light.vo.ImgVO $param_ImgVO_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_setTabledata_40, new java.lang.Object[] {$param_ImgVO_1}, -524909182176672575L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setTabledataDia()
    public java.util.List setTabledataDia()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_setTabledataDia_41, null, -6961119744916257354L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setTabledataGbk()
    public java.util.List setTabledataGbk()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_setTabledataGbk_42, null, -8864739332034746400L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of setTabledataimg()
    public java.util.List setTabledataimg()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_setTabledataimg_43, null, -4043645422568780262L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of update(DiaVO)
    public void update(com.light.vo.DiaVO $param_DiaVO_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_update_44, new java.lang.Object[] {$param_DiaVO_1}, -9162976052330438556L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of update(GbkVO)
    public void update(com.light.vo.GbkVO $param_GbkVO_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_update_45, new java.lang.Object[] {$param_GbkVO_1}, 3708710906464707635L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of update(HpVO)
    public void update(com.light.vo.HpVO $param_HpVO_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_update_46, new java.lang.Object[] {$param_HpVO_1}, 2267545003064835729L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of update(ImgVO)
    public void update(com.light.vo.ImgVO $param_ImgVO_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_update_47, new java.lang.Object[] {$param_ImgVO_1}, 6555125135474642167L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of update(MemVO)
    public void update(com.light.vo.MemVO $param_MemVO_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_update_48, new java.lang.Object[] {$param_MemVO_1}, 5447448691738074304L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of updateMsg(MsgVO)
    public void updateMsg(com.light.vo.MsgVO $param_MsgVO_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_updateMsg_49, new java.lang.Object[] {$param_MsgVO_1}, 3342902330516187517L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of userOnOff(String)
    public java.util.ArrayList userOnOff(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_userOnOff_50, new java.lang.Object[] {$param_String_1}, -108148421668992079L);
	    return ((java.util.ArrayList) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of userSave(String, String)
    public void userSave(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_userSave_51, new java.lang.Object[] {$param_String_1, $param_String_2}, 2118097011399531586L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of userlogOut(String)
    public void userlogOut(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_userlogOut_52, new java.lang.Object[] {$param_String_1}, 4283787935534593683L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
